apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfoaltinn-retry
  namespace: flex
  labels:
    team: flex
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1    # Slettes ikke på bakgrunn av diskstørrelse
    retentionHours: 336  # 2 uker
  acl:
    - team: flex
      application: syfoaltinn
      access: readwrite

