apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: sykepengesoknad-altinn-retry
  namespace: flex
  labels:
    team: flex
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1    # Slettes ikke på bakgrunn av diskstørrelse
    retentionHours: 336  # 2 uker
  acl:
    - team: flex
      application: sykepengesoknad-altinn
      access: readwrite

