apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-altinn
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuTresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 120
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/isReady
    initialDelay: 120
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: PDFGEN_URL
      value: https://flex-sykepengesoknad-pdfgen.dev.intern.nav.no
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL
      value: https://modapp-q1.adeo.no/ereg/ws/OrganisasjonService/v4
    - name: LAGREJURIDISKLOGG_REST_URL
      value: https://app-q1.adeo.no/juridisklogg/api/rest/logg
    - name: EKSTERN_ALTINN_BEHANDLEALTINNMELDING_V1_ENDPOINTURL
      value: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/BehandleAltinnMelding/v1
    - name: FASIT_ENVIRONMENT_NAME
      value: q1
    - name: PDL_API_AAD_CLIENT_ID
      value: dev-fss.pdl.pdl-api
