apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-altinn
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: sykepengesoknad-altinn-db
            envVarPrefix: DB
    buckets:
      - name: {{ bucketName }}
        publicAccessPrevention: true
        retentionPeriodDays: {{ retentionDays }}
        lifecycleCondition:
          age: {{ retentionDays }}
          withState: ANY
  accessPolicy:
    outbound:
      rules:
        - application: flex-sykepengesoknad-pdfgen
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  envFrom:
    - secret: altinn-serviceuser
  env:
    - name: BUCKET_NAME
      value: {{ bucketName }}
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
