apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-altinn
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuTresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  readiness:
    path: /internal/health
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 768Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        databases:
          - name: sykepengesoknad-altinn-db
            envVarPrefix: DB
    buckets:
      - name: {{ bucketName }}
        retentionPeriodDays: {{ retentionDays }}
        lifecycleCondition:
          age: {{ retentionDays }}
          withState: ANY
  accessPolicy:
    outbound:
      rules:
        - application: flex-sykepengesoknad-pdfgen
  envFrom:
    - secret: altinn-serviceuser
  env:
    - name: BUCKET_NAME
      value: {{ bucketName }}
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
