kafkaPool: nav-prod
db_tier: db-custom-1-3840
environment: prod
bucketName: flex-sykepengesoknad-altinn-bucket-prod
retentionDays: '1825'
env:
  PDL_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  PDFGEN_URL: http://flex-sykepengesoknad-pdfgen
  ALTINN_URL: https://www.altinn.no
