DROP TABLE SENDT_SOKNAD;

CREATE TABLE SENDT_SOKNAD
(
    ID                 VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKEPENGESOKNAD_ID VARCHAR(100)             NOT NULL UNIQUE,
    SENDT              TIMESTAMP WITH TIME ZONE NOT NULL
);


