CREATE TABLE EGENMELDING_FRA_SYKMELDING
(
    ID               VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKMELDING_ID    VARCHAR UNIQUE NOT NULL,
    EGENMELDINGSSVAR VARCHAR        NOT NULL,
    SOKNAD_FOM       DATE           NULL
);
