name: "Deploy topic"
on:
  push:
    paths:
      - nais/topics/**
      - .github/workflows/topic.yml
jobs:
  deploy-topic:
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@main
    permissions:
      id-token: write
    with:
      app: ${{ github.event.repository.name }}-topic
      nais-template: nais/topics/sykepengesoknad-altinn-retry-topic.yaml
    secrets: inherit
